AllCops:
  NewCops: enable
  Exclude:
    - .git/**/*
    - db/migrate/**/*
    - db/schema.rb
    - bin/**/*
    - node_modules/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Rakefile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/simple_form_bootstrap.rb

require:
  - rubocop-rails

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
