version: '3.9'

services:
  web:
    build: docker
    command: bin/dev
    tty: true
    # command: tail -f /dev/null
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:15-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db-volume:
  bundle-volume:
