version: '3.9'

services:
  web:
    build: docker
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:15-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db-volume:
